### ISSUE TITLE
Enforce accessibility best practices by making some parameters mandatory 

### ISSUE THREAD

**Issue by GlynnPhillips** [Financial-Times/o-banner#115]
[type]: A feature request

## What

Enforce accessibility best practices by making some parameters mandatory such as the `closeButtonLabel`

## Details

We often see issues raised in the DAC accessibility report that are caused by people using components and not using some of the options. There may be lots of reasons why this happen.

Sometimes when these are raised we try to do our best at creating a default experience but these often fall short as they are missing the context required from the parent application.

We could throw an error in a similar way to the errors thrown for not setting a theme https://github.com/Financial-Times/o-banner/blob/master/src/js/banner.js#L52

As this would need to be a new breaking changing we would want to review all the options along with any options we don't currently have but would be nice to add at the same time for accessibility improvements.

This issue is on o-banner because I have just been updating the use of o-banner to add the `closeButtonLabel` parameter in n-messaging-client but I imagine a change like this would be useful across many Origami components.

**Comment by GlynnPhillips** [comment]
Related changes being made in n-messaging-client that I mentioned https://github.com/Financial-Times/n-messaging-client/pull/303

**Comment by JakeChampion** [comment]
@GlynnPhillips this is a great idea.

As this is proposing a new pattern which relates to many components, would you be able to open it as a [new pattern proposal](https://github.com/Financial-Times/origami/blob/master/.github/CONTRIBUTING.md#propose-a-new-component-or-pattern) over on our Origami repository? It would be really useful to see this proposal over on that repo as we are hoping to get more people outside the Origami team feeling comfortable making proposals such as this :-)

**Comment by GlynnPhillips** [comment]
Thanks @JakeChampion I wasn't sure where to make larger pattern suggestions.. I should have at least tried to find out 😂 I will move it across asap
