### ISSUE TITLE
V2 Updates

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-banner#18]
To avoid clashes with Opinions and to give marketing a stronger typographic style with have made a few updates to the marketing variants of o-banner. 

Main changes are an increase in heading type sizes and use of a secondary heading. 
The addition of a 6px rule under the headings. 

Changing the colours so the default secondary version using white for the background. 100% Black for the text and Teal (90 brightness) for the rule. And for the standout the rule and all text are 100% Black with Teal (90 brightness) for the background. 

Sketch file can be found here: 
https://drive.google.com/open?id=0B8f0KVx7ey79cTh2NUVIZkdFQlk

**Comment by rowanmanning** [comment]
Just an update to say that this is on my radar, @draysonandstock. Priority-wise, is there a time you'd ideally like this done by?

**Comment by draysonandstock** [comment]
Hi Rowan, if need be the white secondary version would be the one we need first as we will be using that version for the Lionel slider. So would be going live with it as soon as it's ready. 

Cheers, 
James

**Comment by rowanmanning** [comment]
This has been added in v1.2.0
