### ISSUE TITLE
Removal of margin interfering with styling

### ISSUE THREAD

**Issue by jkerr321** [Financial-Times/o-banner#27]
The following code is interfering with existing styles:

```
@mixin oBannerContent {
	padding: 0 $_o-banner-spacing;

	// Remove margins from typographic elements within
	// the banner, as these mess with the spacing
	* {
		margin-top: 0;
		margin-bottom: 0;
	}
```

In the below example, some existing components are being inserted into the banner, and are styled to have margin above and below each element (see the background pic for correct styling). It's possible to add more specific classes on the banner to restyle the components to replace the styles that have been removed, but it feels a bit messy given that they've already been styled in their component state:

![image](https://user-images.githubusercontent.com/17846996/33281738-2ed610bc-d39e-11e7-9294-5119349e9bc8.png)

This is more of a design decision that needs to be made with James D

----

Also, `o-share` icons in the banner are behaving strangely...

![image](https://user-images.githubusercontent.com/17846996/33329787-28a58422-d455-11e7-9d5e-2ab92b8e7e94.png)

![image](https://user-images.githubusercontent.com/17846996/33329791-2c6ec1fe-d455-11e7-89db-4096faf1b619.png)

The two sets of icons are from the same component and styled the same, but in the second pic the icons have been inserted into an `o-banner`. For now I've added the following code to the icons in the banner to rectify the issue:

```
                ul {
			margin: 0;
		}

		ul li {
			padding-left: 0;
		}

		ul li:before {
			content: "";
		}
```

**Comment by rowanmanning** [comment]
This is mostly fixed in #33, will discuss further next week.
