### ISSUE TITLE
Bottom border showing on close button

### ISSUE THREAD

**Issue by jkerr321** [Financial-Times/o-banner#28]
![image](https://user-images.githubusercontent.com/17846996/33281890-af476282-d39e-11e7-89d3-abb66ca03763.png)

**Comment by rowanmanning** [comment]
Hey @jkerr321 :) do you have an example page where this is happening that I could access? The demos are fine and I need to work out how to replicate this

**Comment by jkerr321** [comment]
Yep - if you pull `n-invite-colleagues` and run the demo you'll see it. 

(The other banner issues we discussed are also in that repo - in `main.scss` the styling that I've put in to work around the issues is clearly commented, so if you comment that out then `make build demo` you should see all the things) 😊
