### ISSUE TITLE
CSS class name semantics

### ISSUE THREAD

**Issue by debugwand** [Financial-Times/o-banner#50]
We require a high-contrast style for important items. Currently white background styling is tied to 'marketing' in the class name but we will be using this style for things like the cookie consent banner when it is at the bottom of the page.

Note that 'white' won't be a good fit because design have mentioned they may wish to change it from white to something else, the relevant piece of information is that it is important or priority.

**Comment by rowanmanning** [comment]
This is being released as part of v2, which will then be used in the updated o-cookie-message. Hopefully some time this week
