### ISSUE TITLE
To add an XS variant to o-banner. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-banner#52]
To add an XS version of o-banner which will form the basis for the new Cookie banner. 

**Sketch file is here:**
https://drive.google.com/file/d/0B8f0KVx7ey79VHpUNzAtdkVlc1E/view

_**Points to consider:**_ 
- As is currently the case with o-banner-small there is a downwards shift in type size at smallest breakpoints. 
- The button and link should be optional at all breakpoints. 
- If the horizontal rule could be optional too that would be great. 
- For mobile look at the current small banner and we can then go through it in browser. 

![screen shot 2018-06-05 at 15 02 40](https://user-images.githubusercontent.com/11214093/40982002-2f0fafc2-68d4-11e8-8edc-99c4597d246d.png)

**Comment by rowanmanning** [comment]
Completed and going to land in v2
